# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controllers that will be available for the controller manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rrbot_controller:
      type: rrbot_controller/RRBotController

# Properties of the custom controler and definition of joints to use
rrbot_controller:
  ros__parameters:
    joints:
      - vf_container_wall_motor_1_joint
    interface_name: position